services:
  nexus:
    image: sonatype/nexus3:latest
    restart: always
    volumes:
      - "./nexus-data:/nexus-data"
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/nexus.local.crt:/etc/nginx/ssl/nexus.crt:ro
      - ./cert/nexus.local.key:/etc/nginx/ssl/nexus.key:ro
    depends_on:
      - nexus