apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: <master 1 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    installFlags:
    - --disable-components=coredns
    - --disable-components=autopilot
    - --disable-components=windows-node
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
  - ssh:
      address: <master 2 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    installFlags:
    - --disable-components=coredns
    - --disable-components=autopilot
    - --disable-components=windows-node
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
  - ssh:
      address: <master 3 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    installFlags:
    - --disable-components=coredns
    - --disable-components=autopilot
    - --disable-components=windows-node
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
  - ssh:
      address: <worker 1 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    installFlags:
    - --kubelet-extra-args="--cluster-dns=<10th IP in the Service CIDR>"
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
    hooks:
      apply:
        after:
          - sudo k0s ctr images prune --all
  - ssh:
      address: <worker 2 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    installFlags:
    - --kubelet-extra-args="--cluster-dns=<10th IP in the Service CIDR>"
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
    hooks:
      apply:
        after:
          - sudo k0s ctr images prune --all
  - ssh:
      address: <worker 3 ip>
      user: <user>
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    installFlags:
    - --kubelet-extra-args="--cluster-dns=<10th IP in the Service CIDR>"
    - --debug
    uploadBinary: false
    k0sDownloadURL: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-%v-%p%x
    privateInterface: enp0s3
    files:
      - name: bundle-file
        src: https://<local repo>/repository/github/k0sproject/k0s/releases/download/%v/k0s-airgap-bundle-%v-%p%x
        dstDir: /var/lib/k0s/images/
        perm: 0755
    hooks:
      apply:
        after:
          - sudo k0s ctr images prune --all
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m
      timeout: 5m
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
    evictTaint:
      enabled: true
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoSchedule
    concurrency:
      limit: 30
      uploads: 6
  k0s:
    version: v1.33.3+k0s.0
    config:
      spec:
        api:
          sans:
          - <keepalive vip>
        network:
          provider: calico
          calico:
            wireguard: true
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
          controlPlaneLoadBalancing:
            enabled: true
            type: Keepalived
            keepalived:
              vrrpInstances:
              - virtualIPs: ["<keepalive vip>/32"]
                authPass: "ieLoo0id"
              virtualServers:
              - ipAddress: "<keepalive vip>"
        images:
          default_pull_policy: Never
        telemetry:
          enabled: false
        extensions:
          helm:
            concurrencyLevel: 1
            repositories:
            - name: ceph-csi
              url: https://<local repo>/ceph
            - name: coredns
              url: https://<local repo>/coredns
            charts:
            - name: coredns
              chartname: coredns/coredns
              version: "1.43.0"
              timeout: 5m
              order: 1
              values: |
                image:
                  repository: <local repo>/coredns/coredns
                replicaCount: 2
                servers:
                - zones:
                  - zone: .
                  port: 53
                  # -- expose the service on a different port
                  # servicePort: 5353
                  # If serviceType is nodePort you can specify nodePort here
                  # nodePort: 30053
                  # hostPort: 53
                  plugins:
                  - name: errors
                  # Serves a /health endpoint on :8080, required for livenessProbe
                  - name: health
                    configBlock: |-
                      lameduck 10s
                  # Serves a /ready endpoint on :8181, required for readinessProbe
                  - name: ready
                  # Required to query kubernetes API for data
                  - name: kubernetes
                    parameters: cluster.local in-addr.arpa
                    configBlock: |-
                      pods insecure
                      fallthrough in-addr.arpa
                      ttl 5
                  # Serves a /metrics endpoint on :9153, required for serviceMonitor
                  - name: prometheus
                    parameters: 0.0.0.0:9153
                  - name: forward
                    parameters: . /etc/resolv.conf
                  - name: cache
                    parameters: 5
                  - name: loop
                  - name: reload
                  - name: loadbalance
                livenessProbe:
                  enabled: true
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
                  successThreshold: 1
                readinessProbe:
                  enabled: true
                  initialDelaySeconds: 30
                  periodSeconds: 2
                  timeoutSeconds: 5
                  failureThreshold: 3
                  successThreshold: 1
                podDisruptionBudget:
                  minAvailable: "50%"
                autoscaler:
                  enabled: false
                serviceType: "ClusterIP"
                service:
                  clusterIP: "<10th IP in the Service CIDR>"
              namespace: kube-system
            - name: ceph-csi-rbd
              chartname: ceph-csi/ceph-csi-rbd
              version: "3.14.1"
              timeout: 5m
              order: 2
              values: |
                rbac:
                  create: true
                serviceAccounts:
                  nodeplugin:
                    create: true
                  provisioner:
                    create: true
                csiConfig:
                  - clusterID: "<cluster ID>"
                    monitors:
                      - "<mon 1 ip>:<mon 1 port>"
                      - "<mon 2 ip>:<mon 2 port>"
                      - "<mon 3 ip>:<mon 3 port>"

                nodeplugin:
                  name: nodeplugin
                  registrar:
                    image:
                      repository: <local repo>/sig-storage/csi-node-driver-registrar
                  plugin:
                    image:
                      repository: <local repo>/cephcsi/cephcsi
                provisioner:
                  name: provisioner
                  replicaCount: 3
                  strategy:
                    type: RollingUpdate
                    rollingUpdate:
                      maxUnavailable: 50%
                  provisioner:
                    image:
                      repository: <local repo>/sig-storage/csi-provisioner
                    resources: {}
                  attacher:
                    name: attacher
                    enabled: true
                    image:
                      repository: <local repo>/sig-storage/csi-attacher
                  resizer:
                    name: resizer
                    enabled: true
                    image:
                      repository: <local repo>/sig-storage/csi-resizer
                  snapshotter:
                    image:
                      repository: <local repo>/sig-storage/csi-snapshotter

                storageClass:
                  create: true
                  name: csi-rbd-sc
                  annotations:
                    storageclass.kubernetes.io/is-default-class: "true"
                  clusterID: <cluster ID>
                  pool: kubernetes
                  provisionerSecret: csi-rbd-secret
                  provisionerSecretNamespace: ""
                  controllerExpandSecret: csi-rbd-secret
                  controllerExpandSecretNamespace: ""
                  nodeStageSecret: csi-rbd-secret
                  nodeStageSecretNamespace: ""
                  fstype: ext4
                  reclaimPolicy: Delete
                  allowVolumeExpansion: true

                secret:
                  create: true
                  name: csi-rbd-secret
                  userID: kubernetes
                  userKey: <token>
                kubeletDir: /var/lib/k0s/kubelet
              namespace: ceph-csi-rbd